
server:
  port: 9004

spring:
  application:
    name: consumer-service


eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka

#开启feign支持
feign:
  httpclient:
    enabled: true

logging:
  level:
    com.lily: debug
